
version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
    assignees:
      - "Soumyadeep-ai"

  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    labels:
      - "ci"
      - "github-actions"
    assignees:
      - "Soumyadeep-ai"
