AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

plugins:
  - rubocop-rspec
  - rubocop-rake

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/**/*_spec.rb'
    - 'spec/console_kit/railtie_spec.rb'

RSpec/SpecFilePathFormat:
  Exclude:
    - 'spec/generators/**/*_spec.rb'
