AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

plugins:
  - rubocop-rspec
  - rubocop-rake

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

RSpec/VerifiedDoubles:
  Exclude:
    - 'spec/console_kit/connections/**/*_spec.rb'

