# frozen_string_literal: true

# Auto-generated by ConsoleKit
# 👉 Customize the following configuration to fit your application

Rails.application.config.after_initialize do
  ConsoleKit.configure do |config|
    # TODO: Set your tenants source, example:
    # {
    #   tenant_a: {
    #     constants: {
    #       shard: :shard_1,
    #       mongo_db: 'mongo_db_1',
    #       partner_code: 'partner_a'
    #     }
    #   },
    #   tenant_b: {
    #     constants: {
    #       shard: :shard_2,
    #       mongo_db: 'mongo_db_2',
    #       partner_code: 'partner_b'
    #     }
    #   }
    # }
    config.tenants = nil

    # TODO: Set your context class (e.g., CurrentContext)
    config.context_class = nil

    # Toggle pretty output on/off (default: true)
    config.pretty_output = true

    if config.tenants.nil?
      warn '[ConsoleKit] Warning: `tenants` is not configured. Please set it in config/initializers/console_kit.rb'
    end

    if config.context_class.nil?
      warn '[ConsoleKit] Warning: `context_class` is not configured. Please set it in config/initializers/console_kit.rb'
    end
  end
end
