# frozen_string_literal: true

# Auto-generated by ConsoleKit
# 👉 Customize the following configuration to fit your application

Rails.application.config.after_initialize do
  ConsoleKit.configure do |config|
    # TODO: Set your tenants source in the following format
    # {
    #   key:
    #   {
    #     constants:
    #     {
    #       shard: # Active Record Shard
    #       mongo_db: # Mongo Shard (If Mongo Is being used)
    #       partner_code: # If partners are needed
    #     }
    #   }
    # }
    config.tenants = nil

    # TODO: Set your context class (e.g., CurrentContext)
    config.context_class = nil

    # TODO: Toggle the pretty output on/off
    config.pretty_output = true
  end
end
