name: RSpec Test Suite

on:
  pull_request:
    branches: [master]

permissions:
  contents: read
  pull-requests: write

jobs:
  rspec:
    runs-on: ubuntu-latest
    name: Run RSpec and comment on PR

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.4

      - name: Install dependencies
        run: bundle install

      - name: Run RSpec with summary
        id: rspec_test
        run: |
          bundle exec rspec --format documentation | tee result.txt

      - name: Extract test summary
        id: test_summary
        run: |
          summary=$(tail -n 10 result.txt | grep -E 'examples?,|failures?|pending?' | tr '\n' ' ')
          echo "summary=${summary}" >> $GITHUB_OUTPUT

      - name: Comment test results on PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ✅ **RSpec Test Summary**
            ```
            ${{ steps.test_summary.outputs.summary }}
            ```
